"""
HTML report formatter with CSS styling and dark/light theme support.
"""

from typing import Dict, List, Any
from .utils import strip_rich_markup, strip_ansi_codes, escape_html
from .styles import HTML_STYLE


class HTMLFormatter:
    """Format report sections as styled HTML with embedded CSS."""
    
    def __init__(self, dll_imports_data: Dict = None, indicators_dict: Dict = None):
        self.dll_imports_data = dll_imports_data or {}
        self.indicators_dict = indicators_dict or {}
    
    def format(self, sections: List[Dict], full_output: str = "") -> str:
        """Generate clean HTML report with analysis sections and theme support."""
        clean_output = strip_ansi_codes(full_output or "")
        
        html_parts = [
            "<!DOCTYPE html>",
            "<html lang='en'>",
            "<head>",
            "<meta charset='UTF-8'>",
            "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
            "<title>PE Malware Analysis Report</title>",
            f"<style>{HTML_STYLE}</style>",
            "</head>",
            "<body>",

        ]
        
        # Analysis sections from full output
        if clean_output:
            parsed_sections = self._parse_analysis(clean_output)
            for idx, section in enumerate(parsed_sections):
                section_html = self._format_analysis_section(section['title'], section['content'])
                
                if section_html and "Static Indicators" in section['title']:
                    section_html_modified = section_html.rstrip('</div>\n</div>\n')
                    
                    if self.indicators_dict and self.indicators_dict.get('ascii'):
                        ascii_strings = self.indicators_dict.get('ascii', [])
                        if ascii_strings:
                            section_html_modified += self._format_string_subsection("ASCII Strings Detected", ascii_strings, "ascii-strings-spoiler")
                    
                    if self.indicators_dict and self.indicators_dict.get('unicode'):
                        unicode_strings = self.indicators_dict.get('unicode', [])
                        if unicode_strings:
                            section_html_modified += self._format_string_subsection("Unicode Strings Detected", unicode_strings, "unicode-strings-spoiler")
                    
                    section_html_modified += "</div>\n</div>\n"
                    html_parts.append(section_html_modified)
                else:
                    html_parts.append(section_html)
        
        # Structured sections
        for section in sections:
            if section:
                html_parts.extend(self._format_section(section))
        
        # Footer
        html_parts.extend([
            f"<p class='footer'>Generated by PE Malware Triage Tool 1.0.0 | Static Analysis Only | © 2025</p>",
            "</body></html>",
        ])
        
        return "\n".join(html_parts)

    
    def _parse_analysis(self, full_output: str) -> List[Dict]:
        """Parse full output into logical sections (ordered, no duplicates)."""
        if not full_output:
            return []
        
        # Maintain section order and prevent duplicates
        sections_dict = {}
        sections_order = []
        lines = full_output.split('\n')
        
        # Section headers to match (order matters - match most specific first)
        known_sections = [
            'File Identification', 'Privilege & Execution Context',
            'PE Headers', 'Section Analysis',
            'Imported DLLs & Functions', 'ADVANCED ANALYSIS',
            'Static Indicators', 'Unified Threat Classification', 'Advanced Packing Detection',
            'Compiler & Build Environment', 'Entropy Analysis', 'Import Anomalies',
            'String Analysis', 'Packer Detection', 'Overlay Analysis',
            'DLL Hijacking Detection', 'COM Hijacking', 'Anti-Analysis Techniques', 'Mutex Signatures',
            'Shellcode Patterns Detection', 'Threat Assessment',
            'Detection Breakdown', 'Recommended Action','Sandbox Evasion / Task Scheduling','Persistence Mechanisms',
            'Mutex Analysis'
        ]
        
        current_section = None
        current_content = []
        
        for line in lines:
            line_stripped = line.strip()
            
            # Check if line is a section header (exact or contains header)
            is_header = False
            for header in known_sections:
                if header in line_stripped and len(line_stripped) < 100:  # Avoid matching data rows
                    is_header = True
                    break
            
            if is_header and line_stripped:
                # Save previous section (only if not already seen)
                if current_section and current_section not in sections_dict:
                    # Filter out empty lines at start/end
                    while current_content and not current_content[0].strip():
                        current_content.pop(0)
                    while current_content and not current_content[-1].strip():
                        current_content.pop()
                    # Save even if empty content (section header only)
                    sections_dict[current_section] = current_content
                    sections_order.append(current_section)
                
                # Start new section
                current_section = line_stripped
                current_content = []
            elif current_section is not None:
                current_content.append(line)
        
        # Save last section (only if not already seen)
        if current_section and current_section not in sections_dict:
            while current_content and not current_content[0].strip():
                current_content.pop(0)
            while current_content and not current_content[-1].strip():
                current_content.pop()
            # Save even if empty content (section header only)
            sections_dict[current_section] = current_content
            sections_order.append(current_section)
        
        # Return sections in order with no duplicates
        return [{'title': title, 'content': sections_dict[title]} for title in sections_order]
    
    def _create_spoiler(self, spoiler_id: str, label: str, content: str) -> str:
        """Create pure CSS spoiler."""
        return (f'<input type="checkbox" id="{spoiler_id}" class="spoiler-checkbox">\n'
                f'<label for="{spoiler_id}" class="spoiler-toggle">{label}</label>\n'
                f'<div class="spoiler-content">\n{content}\n</div>')
    
    def _format_analysis_section(self, title: str, content: List[str]) -> str:
        """Format analysis section with HTML and spoiler toggles for long content."""
        if not content or not any(c.strip() for c in content):
            return ""
        
        title_escaped = escape_html(title)
        clean_content = [strip_ansi_codes(line) for line in content]
        
        # Special handling for Unified Threat Classification - plain text box with color coding
        if "Unified Threat Classification" in title:
            html = f"<div class='analysis-section'>\n<div class='section-title'>{title_escaped}</div>\n"
            html += f"<div class='section-content'>\n<pre style='background: #0a0a0a; padding: 15px; border-radius: 4px; overflow-x: auto; font-family: monospace; line-height: 1.6; color: #d4dce6;'>"
            
            for line in clean_content:
                if not line.strip():
                    html += "\n"
                    continue
                
                # Color code by severity
                if "CRITICAL" in line:
                    html += f"<span style='color: #ff4444;'>{escape_html(line)}</span>\n"
                elif "HIGH" in line and "[" in line and "]" in line:  # Threat line with severity
                    html += f"<span style='color: #ffaa00;'>{escape_html(line)}</span>\n"
                elif "MEDIUM" in line and "[" in line and "]" in line:
                    html += f"<span style='color: #ffdd44;'>{escape_html(line)}</span>\n"
                elif "LOW" in line and "[" in line and "]" in line:
                    html += f"<span style='color: #44dd44;'>{escape_html(line)}</span>\n"
                else:
                    html += f"{escape_html(line)}\n"
            
            html += "</pre>\n</div>\n</div>"
            return html
        
        is_critical = any('CRITICAL' in line for line in clean_content)
        is_high = any('HIGH' in line for line in clean_content) and not is_critical
        color_class = "alert-critical" if is_critical else ("alert-high" if is_high else "")
        
        html = f"<div class='analysis-section {color_class}'>\n<div class='section-title'>{title_escaped}</div>\n<div class='section-content'>\n"
        
        in_table = False
        spoiler_counter = 0
        i = 0
        is_imports_section = "Imported DLL" in title
        
        # Check if section has hierarchical structure with [!] markers - now more comprehensive
        has_hierarchical_sections = any('[!]' in line for line in clean_content)
        
        while i < len(clean_content):
            line = strip_ansi_codes(clean_content[i]).rstrip()
            if not line:
                i += 1
                continue
            
            # Skip pure separator lines (====, ----, etc.)
            if all(c in '═─━│=- ' for c in line) and len(set(c for c in line if c not in ' ')) == 1:
                i += 1
                continue
            
            # Special handling for hierarchical sections with [!] subsection markers
            if has_hierarchical_sections and '[!]' in line:
                # This is a subsection header like "[!] Anti-Debug Techniques"
                subsection_title = line.replace('[!]', '').strip()
                html += f"<div class='subsection-title' style='margin-top: 12px; font-weight: 600; color: #14b8a6;'>{escape_html(subsection_title)}</div>\n"
                
                # Look ahead for Detection: line
                j = i + 1
                detection_text = ""
                while j < len(clean_content):
                    next_line = strip_ansi_codes(clean_content[j]).rstrip()
                    if not next_line or next_line.startswith('[!]'):
                        break
                    if 'Detection:' in next_line:
                        detection_text = next_line.replace('Detection:', '').strip()
                        break
                    j += 1
                
                if detection_text:
                    html += f"<div class='detection-reason' style='margin-left: 8px; color: #999; font-size: 0.9em; margin-bottom: 8px;'><em>Detection: {escape_html(detection_text)}</em></div>\n"
                    i = j  # Skip the Detection line
                
                # Collect all bullet-point items for this subsection
                items = []
                j = i + 1
                while j < len(clean_content):
                    next_line = strip_ansi_codes(clean_content[j]).rstrip()
                    if not next_line:
                        j += 1
                        continue
                    if next_line.startswith('[!]'):
                        break
                    if next_line.strip().startswith('*'):
                        item_text = next_line.strip()[1:].strip()
                        items.append(item_text)
                        j += 1
                    else:
                        break
                
                # Display items - create spoiler if many items
                if items:
                    # Always create spoiler if items > 10
                    if len(items) > 10:
                        spoiler_counter += 1
                        spoiler_id = f"hijack-spoiler-{spoiler_counter}"
                        # Show first 5 inline + "... and X more"
                        items_inline = ', '.join([escape_html(item) for item in items[:5]])
                        items_html = f"<div style='margin-left: 12px; margin-bottom: 4px; word-break: break-word;'>• {items_inline}</div>\n"
                        items_html += f"<div style='margin-left: 12px; color: #999; font-size: 0.9em;'>... and {len(items) - 5} more</div>"
                        
                        # All items inline in spoiler
                        all_items_inline = ', '.join([escape_html(item) for item in items])
                        spoiler_content = f'<div style="background: rgba(15, 23, 42, 0.7); padding: 12px; border-radius: 4px; word-break: break-word; line-height: 1.6; color: #d4dce6; font-size: 0.9em;">• {all_items_inline}</div>'
                        label = f"View All {len(items)} Items"
                        spoiler_html = self._create_spoiler(spoiler_id, label, spoiler_content)
                        
                        html += items_html + "\n" + spoiler_html + "\n"
                    else:
                        # Show all items inline when 10 or fewer
                        items_inline = ', '.join([escape_html(item) for item in items])
                        html += f"<div style='margin-left: 12px; margin-bottom: 4px; word-break: break-word;'>• {items_inline}</div>\n"
                
                i = j
                continue
            
            # Parse key:value lines
            if ':' in line and len(line.split(':')[0]) < 30:
                key, val = line.split(':', 1)
                key_stripped = key.strip()
                val_stripped = val.strip()
                
                # Collect continuation lines for list fields (lines that don't have a key:)
                j = i + 1
                while j < len(clean_content):
                    next_line = strip_ansi_codes(clean_content[j]).rstrip()
                    # Empty line: skip but continue looking for more continuation lines
                    if not next_line:
                        j += 1
                        continue
                    # If line has [!] marker, it's a new subsection, so stop
                    if '[!]' in next_line:
                        break
                    # If line has a colon, it's a new key:value pair, so stop
                    if ':' in next_line and len(next_line.split(':')[0]) < 30:
                        break
                    # Otherwise, treat it as a continuation line and add to value
                    val_stripped += ", " + next_line.strip()
                    j += 1
                
                # Skip the continuation lines we just processed
                i = j - 1
                
                # Special handling for DLL entries with function lists in Imports section
                if is_imports_section and ('.dll' in key_stripped.lower() or '.drv' in key_stripped.lower()) and self.dll_imports_data:
                    spoiler_counter += 1
                    spoiler_id = f"dll-spoiler-{spoiler_counter}"
                    
                    # Get the actual function list from dll_imports_data
                    functions = []
                    
                    # Try exact match first
                    if key_stripped in self.dll_imports_data:
                        functions = self.dll_imports_data[key_stripped]
                    else:
                        # Try case-insensitive match
                        key_lower = key_stripped.lower()
                        for dll_name, dll_funcs in self.dll_imports_data.items():
                            if dll_name.lower() == key_lower:
                                functions = dll_funcs
                                break
                        
                        # If still not found, try without extension variations
                        if not functions:
                            key_normalized = key_lower
                            for ext in ['.dll', '.drv', '.sys', '.exe']:
                                if key_normalized.endswith(ext):
                                    key_normalized = key_normalized[:-len(ext)]
                                    break
                            
                            for dll_name, dll_funcs in self.dll_imports_data.items():
                                dll_normalized = dll_name.lower()
                                for ext in ['.dll', '.drv', '.sys', '.exe']:
                                    if dll_normalized.endswith(ext):
                                        dll_normalized = dll_normalized[:-len(ext)]
                                        break
                                
                                if dll_normalized == key_normalized:
                                    functions = dll_funcs
                                    break
                    
                    if len(functions) >= 1:
                        # Create spoiler with all functions
                        all_functions_raw = ', '.join([f.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") for f in functions])
                        spoiler_content = f'<div style="background: rgba(15, 23, 42, 0.7); padding: 12px; border-radius: 4px; font-family: monospace; word-break: break-word; line-height: 1.4; color: #d4dce6; font-size: 0.9em;">{all_functions_raw}</div>'
                        
                        label = f"View All {len(functions)} Function{'s' if len(functions) > 1 else ''}"
                        spoiler_html = self._create_spoiler(spoiler_id, label, spoiler_content)
                        
                        html += f"<div class='info-line'><span class='info-key'>{escape_html(key_stripped)}:</span> <span class='info-value'><span class='item-count'>{len(functions)}</span> function{'s' if len(functions) > 1 else ''}</span></div>\n"
                        html += f"{spoiler_html}\n"
                    else:
                        html += f"<div class='info-line'><span class='info-key'>{escape_html(key_stripped)}:</span> <span class='info-value'>{escape_html(val_stripped)}</span></div>\n"
                else:
                    # Check if this is a list field that should be in a spoiler (Mutexes, etc.)
                    items = [item.strip() for item in val_stripped.split(',') if item.strip()]
                    
                    should_spoiler = False
                    show_count = 5
                    
                    if len(items) > 10:  # More than 10 items -> use spoiler
                        should_spoiler = True
                        if 'function' in key_stripped.lower():
                            show_count = 3
                        elif 'url' in key_stripped.lower() or 'domain' in key_stripped.lower():
                            show_count = 3
                        elif 'string' in key_stripped.lower() or 'ascii' in key_stripped.lower():
                            show_count = 8
                        elif 'mutex' in key_stripped.lower():
                            show_count = 5
                        else:
                            show_count = 5
                    
                    if should_spoiler:
                        spoiler_counter += 1
                        spoiler_id = f"list-spoiler-{spoiler_counter}"
                        
                        # Create the collapsible list
                        all_items_raw = ', '.join([item.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") for item in items])
                        spoiler_content = f'<div style="background: rgba(15, 23, 42, 0.7); padding: 12px; border-radius: 4px; font-family: monospace; word-break: break-word; line-height: 1.4; color: #d4dce6; font-size: 0.9em;">{all_items_raw}</div>'
                        label = f"View All {len(items)} {key_stripped}"
                        spoiler_html = self._create_spoiler(spoiler_id, label, spoiler_content)
                        
                        html += f"<div class='info-line'><span class='info-key'>{escape_html(key_stripped)}:</span> <span class='info-value'><span class='item-count'>{len(items)}</span> total items</span></div>\n"
                        html += f"{spoiler_html}\n"
                    else:
                        html += f"<div class='info-line'><span class='info-key'>{escape_html(key_stripped)}:</span> <span class='info-value'>{escape_html(val_stripped)}</span></div>\n"
            elif any(c in line for c in ['─', '│', '═', '━', '•', '─']) or (line.startswith('•') and '─' in line) or (line.count(' ') > 5 and len(line) > 40 and line[0] not in '* +-'):
                if not in_table:
                    html += "<pre class='analysis-table'>\n"
                    in_table = True
                html += escape_html(line) + "\n"
            else:
                if in_table:
                    html += "</pre>\n"
                    in_table = False
                
                if line.startswith('*') or line.startswith('+') or line.startswith('-'):
                    color = 'critical' if 'CRITICAL' in line else ('high' if 'HIGH' in line else 'medium')
                    html += f"<div class='finding {color}'>• {escape_html(line[1:].strip())}</div>\n"
                else:
                    html += f"<div class='text-default'>{escape_html(line)}</div>\n"
            
            i += 1
        
        if in_table:
            html += "</pre>\n"
        
        html += "</div>\n</div>\n"
        return html
    
    def _format_string_section(self, title: str, strings: List[str], spoiler_id: str) -> str:
        """Format ASCII/Unicode string section with spoiler."""
        html = f"<div class='section'>\n"
        html += f"<h2>🔤 {escape_html(title)}</h2>\n"
        html += f"<div class='analysis-section'>\n"
        html += f"<div class='info-line'><span class='info-key'>{escape_html(title)}:</span> <span class='info-value'><span class='item-count'>{len(strings)}</span> total items</span></div>\n"
        
        # Create spoiler for all strings
        all_items_raw = ', '.join([s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") for s in strings])
        spoiler_content = f'<div style="background: rgba(15, 23, 42, 0.7); padding: 12px; border-radius: 4px; font-family: monospace; word-break: break-word; line-height: 1.4; color: #d4dce6; font-size: 0.9em; max-height: 400px; overflow-y: auto;">{all_items_raw}</div>'
        label = f"View All {len(strings)} {title.split()[0]}"
        spoiler_html = self._create_spoiler(spoiler_id, label, spoiler_content)
        
        html += f"{spoiler_html}\n"
        html += f"</div>\n</div>\n"
        return html
    
    def _format_string_subsection(self, title: str, strings: List[str], spoiler_id: str) -> str:
        """Format ASCII/Unicode string subsection (as part of Static Indicators section, not standalone)."""
        html = ""
        html += f"<div class='text-subtitle'>🔤 {escape_html(title)}</div>\n"
        html += f"<div class='info-line'><span class='info-key'>{escape_html(title)}:</span> <span class='info-value'><span class='item-count'>{len(strings)}</span> total items</span></div>\n"
        
        # Create spoiler for all strings
        all_items_raw = ', '.join([s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;") for s in strings])
        spoiler_content = f'<div style="background: rgba(15, 23, 42, 0.7); padding: 12px; border-radius: 4px; font-family: monospace; word-break: break-word; line-height: 1.4; color: #d4dce6; font-size: 0.9em; max-height: 400px; overflow-y: auto;">{all_items_raw}</div>'
        label = f"View All {len(strings)} {title.split()[0]}"
        spoiler_html = self._create_spoiler(spoiler_id, label, spoiler_content)
        
        html += f"{spoiler_html}\n"
        return html

    def _format_section(self, section: Dict) -> List[str]:
        """Format a structured section dict to HTML with color-coded fields."""
        if not section:
            return []
        
        html_lines = []
        title = section.get("title", "Section")
        data = section.get("data", {})
        
        if not data:
            return []
        
        html_lines.append(f"<div class='section'>")
        html_lines.append(f"<h2>{escape_html(title)}</h2>")
        
        for key, value in data.items():
            if value is None or (isinstance(value, (list, dict)) and not value):
                continue
            
            if isinstance(value, dict):
                html_lines.append(f"<div class='info-line'>")
                html_lines.append(f"<span class='info-key'>{escape_html(str(key))}:</span>")
                html_lines.append("<span class='info-value'>")
                for sub_key, sub_value in value.items():
                    html_lines.append(f"<div>{escape_html(str(sub_key))}: {escape_html(str(sub_value))}</div>")
                html_lines.append("</span></div>")
            elif isinstance(value, list):
                if value:
                    html_lines.append(f"<div class='info-line'>")
                    html_lines.append(f"<span class='info-key'>{escape_html(str(key))}:</span>")
                    html_lines.append(f"<span class='info-value'><span class='item-count'>{len(value)}</span> items</span>")
                    html_lines.append("</div>")
            else:
                html_lines.append(f"<div class='info-line'>")
                html_lines.append(f"<span class='info-key'>{escape_html(str(key))}:</span>")
                html_lines.append(f"<span class='info-value'>{escape_html(str(value))}</span>")
                html_lines.append("</div>")
        
        html_lines.append("</div>")
        return html_lines


